// Code generated by gobind. DO NOT EDIT.

// Java class libv2ray.ProtectedDialer is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java github.com/2dust/AndroidLibXrayLite
package libv2ray;

import go.Seq;

/**
 * ProtectedDialer ...
 */
public final class ProtectedDialer implements Seq.Proxy {
	static { Libv2ray.touch(); }
	
	private final int refnum;
	
	@Override public final int incRefnum() {
	      Seq.incGoRef(refnum, this);
	      return refnum;
	}
	
	ProtectedDialer(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
	
	public ProtectedDialer() { this.refnum = __New(); Seq.trackGoRef(refnum, this); }
	
	private static native int __New();
	
	// skipped method ProtectedDialer.DestIpAddress with unsupported parameter or return types
	
	// skipped method ProtectedDialer.Dial with unsupported parameter or return types
	
	// skipped method ProtectedDialer.Init with unsupported parameter or return types
	
	public native boolean isVServerReady();
	// skipped method ProtectedDialer.PrepareDomain with unsupported parameter or return types
	
	public native void prepareResolveChan();
	public native boolean protect(long p0);
	// skipped method ProtectedDialer.ResolveChan with unsupported parameter or return types
	
	@Override public boolean equals(Object o) {
		if (o == null || !(o instanceof ProtectedDialer)) {
		    return false;
		}
		ProtectedDialer that = (ProtectedDialer)o;
		return true;
	}
	
	@Override public int hashCode() {
	    return java.util.Arrays.hashCode(new Object[] {});
	}
	
	@Override public String toString() {
		StringBuilder b = new StringBuilder();
		b.append("ProtectedDialer").append("{");
		return b.append("}").toString();
	}
}

