// Code generated by gobind. DO NOT EDIT.

// Java class libv2ray.V2RayVPNServiceSupportsSet is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java github.com/2dust/AndroidLibXrayLite
package libv2ray;

import go.Seq;

/**
 * V2RayVPNServiceSupportsSet To support Android VPN mode
 */
public interface V2RayVPNServiceSupportsSet {
	public long onEmitStatus(long p0, String p1);
	public long prepare();
	public boolean protect(long p0);
	public long setup(String Conf);
	public long shutdown();
	
}

